if [ -z ${FEDISEER_API_URL+x} ]; then
  FEDISEER_API_URL=https://fediseer.com/api
fi
if [ -z ${FEDISEER_API_VERSION+x} ]; then
  FEDISEER_API_VERSION=v1
fi
if [ -z ${FEDISEER_APP_NAME+x} ]; then
  FEDISEER_APP_NAME=FediseerGUI
fi
if [ -z ${FEDISEER_APP_MAINTAINER+x} ]; then
  echo "Maintainer must be specified using the FEDISEER_APP_MAINTAINER env variable."
  exit 1
fi
if [ -z ${FEDISEER_APP_MAINTAINER+x} ]; then
  echo "Maintainer must be specified using the FEDISEER_APP_MAINTAINER env variable."
  exit 1
fi
if [ -z ${FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES+x} ]; then
  FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES=__all__
fi
if [ -z ${FEDISEER_SOURCE_CODE_LINK+x} ]; then
  FEDISEER_SOURCE_CODE_LINK=https://github.com/Fediseer/FediseerGUI
fi
if [ -z ${FEDISEER_APP_VERSION+x} ]; then
  FEDISEER_APP_VERSION=$(grep appVersion src/environments/environment.ts | cut -c63-97 | rev | cut -c4- | rev)
fi
if [ -z ${FEDISEER_DONATE_LINK+x} ]; then
  FEDISEER_DONATE_LINK=https://liberapay.com/Fediseer/
fi

OLD_IFS=$IFS
FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES_RESULT='['
IFS=','
for INSTANCE in $FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES; do
  FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES_RESULT="$FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES_RESULT '$INSTANCE',"
done
FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES_RESULT="$FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES_RESULT]"
IFS=$OLD_IFS

{
  echo "window['FEDISEER_API_URL'] = '$FEDISEER_API_URL';";
  echo "window['FEDISEER_API_VERSION'] = '$FEDISEER_API_VERSION';"
  echo "window['FEDISEER_APP_NAME'] = '$FEDISEER_APP_NAME';"
  echo "window['FEDISEER_APP_VERSION'] = '$FEDISEER_APP_VERSION';"
  echo "window['FEDISEER_APP_MAINTAINER'] = '$FEDISEER_APP_MAINTAINER';"
  echo "window['FEDISEER_SOURCE_CODE_LINK'] = '$FEDISEER_SOURCE_CODE_LINK';"
  echo "window['FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES_RESULT'] = $FEDISEER_DEFAULT_CENSURE_LIST_FILTER_INSTANCES_RESULT;"
  echo "window['FEDISEER_DONATE_LINK'] = '$FEDISEER_DONATE_LINK';"
} >> /usr/share/nginx/html/assets/runtime-environment.js

