name: Mark issues and PRs as stale
on:
  schedule:
    - cron: '0 8 * * *'

jobs:
  stale_issues:
    runs-on: ubuntu-latest
    name: Mark issues as stale
    env:
      DAYS_BEFORE_STALE: 30
      DAYS_BEFORE_CLOSE: 5
      STALE_LABEL: stale
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/stale@v8
        with:
          stale-issue-message: |
            This issue hasn't seen any activity for ${{ env.DAYS_BEFORE_STALE }} days.
            Please comment (or remove the ${{ env.STALE_LABEL }} label) within ${{ env.DAYS_BEFORE_CLOSE }} days,
            otherwise this issue will be closed.
          close-issue-message: The issue has been closed due to inactivity.
          stale-issue-label: ${{ env.STALE_LABEL }}
          days-before-stale: ${{ env.DAYS_BEFORE_STALE }}
          days-before-close: ${{ env.DAYS_BEFORE_CLOSE }}
